spring.datasource.url=jdbc:postgresql://localhost:5432/diplomadb
spring.datasource.username=postgres
spring.datasource.password=yfayr123
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase сам создаст все таблицы из твоего файла!
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml